services:
  - type: web
    name: edupay-rdc
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn EduPay_RDC.wsgi:application --workers 3 --bind 0.0.0.0:$PORT"
    healthCheckPath: /admin/
    autoDeploy: true
    
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: DJANGO_SETTINGS_MODULE
        value: EduPay_RDC.settings
      - key: DEBUG
        value: "false"
      - key: SECRET_KEY
        generateValue: true
      - key: USE_SQLITE
        value: "true"
      - key: DATABASE_URL
        fromDatabase:
          name: edupay-rdc-db
          property: connectionString
      - key: SITE_URL
        sync: false
      - key: CINETPAY_API_KEY
        sync: false
      - key: CINETPAY_SITE_ID
        sync: false
      - key: CINETPAY_ENV
        value: prod
      - key: DJANGO_SUPERUSER_USERNAME
        sync: false
      - key: DJANGO_SUPERUSER_EMAIL
        sync: false
      - key: DJANGO_SUPERUSER_PASSWORD
        sync: false
      - key: ALLOWED_HOSTS
        value: "localhost,127.0.0.1,testserver,edupay-rdc-p9tw.onrender.com,edupay-rdc.onrender.com,onrender.com,.onrender.com"

databases:
  - name: edupay-rdc-db
    databaseName: edupay_rdc
    user: postgres
    plan: free
    ipAllowList: []
