# Generated by Django 5.2.9 on 2025-12-28 16:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etudiants', '0001_initial'),
        ('frais', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant')),
                ('devise', models.CharField(choices=[('CDF', 'Franc Congolais (CDF)'), ('USD', 'Dollar Américain (USD)')], default='CDF', max_length=3, verbose_name='Devise')),
                ('statut', models.CharField(choices=[('PENDING', 'En attente'), ('SUCCESS', 'Réussi'), ('FAILED', 'Échoué'), ('CANCELLED', 'Annulé')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('reference_flutterwave', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Référence Flutterwave')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ID Transaction')),
                ('commission_plateforme', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Commission plateforme')),
                ('taux_commission', models.DecimalField(decimal_places=2, default=2.0, max_digits=5, verbose_name='Taux de commission (%)')),
                ('date_paiement', models.DateTimeField(blank=True, null=True, verbose_name='Date de paiement')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('message_erreur', models.TextField(blank=True, null=True, verbose_name="Message d'erreur")),
                ('numero_telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Numéro de téléphone')),
                ('operateur', models.CharField(blank=True, max_length=20, null=True, verbose_name='Opérateur Mobile Money')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='etudiants.etudiant', verbose_name='Étudiant')),
                ('frais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='frais.frais', verbose_name='Frais')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['statut', 'date_creation'], name='paiements_p_statut_d72476_idx'), models.Index(fields=['reference_flutterwave'], name='paiements_p_referen_899179_idx'), models.Index(fields=['transaction_id'], name='paiements_p_transac_d978d3_idx')],
            },
        ),
    ]
