# Generated by Django 5.2.9 on 2025-12-28 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='email_paiement',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email pour le paiement'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='methode_paiement',
            field=models.CharField(choices=[('MOBILE_MONEY', 'Mobile Money'), ('CARTE_BANCAIRE', 'Carte Bancaire'), ('QR_CODE', 'QR Code')], default='MOBILE_MONEY', max_length=20, verbose_name='Méthode de paiement'),
        ),
    ]
