# Generated by Django 4.2.7 on 2025-12-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0002_paiement_email_paiement_paiement_methode_paiement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='operateur',
            field=models.CharField(blank=True, choices=[('MPESA', 'M-Pesa'), ('ORANGE', 'Orange Money'), ('AIRTEL', 'Airtel Money'), ('MTN', 'MTN Mobile Money'), ('MOOV', 'Moov Money')], max_length=20, null=True, verbose_name='Opérateur Mobile Money'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='reference_flutterwave',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Référence de paiement'),
        ),
    ]
