# Generated by Django 5.2.9 on 2025-12-28 16:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name="Nom de l'établissement")),
                ('type', models.CharField(choices=[('ECOLE', 'École'), ('INSTITUT', 'Institut Supérieur'), ('UNIVERSITE', 'Université')], max_length=20, verbose_name="Type d'établissement")),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telephone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Format de téléphone invalide', regex='^\\+?1?\\d{9,15}$')], verbose_name='Téléphone')),
                ('adresse', models.TextField(verbose_name='Adresse complète')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo')),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('SUSPENDU', 'Suspendu'), ('EN_ATTENTE', 'En attente de validation')], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('date_inscription', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('admin', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etablissement_admin', to=settings.AUTH_USER_MODEL, verbose_name='Administrateur')),
            ],
            options={
                'verbose_name': 'Établissement',
                'verbose_name_plural': 'Établissements',
                'ordering': ['-date_inscription'],
            },
        ),
        migrations.CreateModel(
            name='ComptePaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operateur', models.CharField(choices=[('MPESA', 'M-Pesa'), ('ORANGE', 'Orange Money'), ('AIRTEL', 'Airtel Money')], max_length=20, verbose_name='Opérateur')),
                ('numero_compte', models.CharField(max_length=50, verbose_name='Numéro de compte')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptes_paiement', to='etablissements.etablissement', verbose_name='Établissement')),
            ],
            options={
                'verbose_name': 'Compte de paiement',
                'verbose_name_plural': 'Comptes de paiement',
                'unique_together': {('etablissement', 'operateur')},
            },
        ),
    ]
