# Generated by Django 5.2.9 on 2025-12-28 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etablissements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comptepaiement',
            name='intitule',
            field=models.CharField(default='', help_text='Ex: Compte principal, Compte Orange Money, etc.', max_length=100, verbose_name='Intitulé du compte'),
        ),
    ]
