# Generated by Django 5.2.9 on 2026-07-10 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etablissements', '0002_comptepaiement_intitule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comptepaiement',
            name='operateur',
            field=models.CharField(choices=[('MPESA', 'M-Pesa'), ('ORANGE', 'Orange Money'), ('AIRTEL', 'Airtel Money'), ('MTN', 'MTN Mobile Money'), ('MOOV', 'Moov Money')], max_length=20, verbose_name='Opérateur'),
        ),
    ]
