# Generated by Django 5.2.9 on 2025-12-28 16:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('GRATUIT', 'Gratuit (Essai)'), ('BASIQUE', 'Basique'), ('PREMIUM', 'Premium'), ('ENTERPRISE', 'Entreprise')], default='GRATUIT', max_length=20, verbose_name="Type d'abonnement")),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('EXPIRE', 'Expiré'), ('SUSPENDU', 'Suspendu'), ('ANNULE', 'Annulé')], default='ACTIF', max_length=20, verbose_name='Statut')),
                ('montant_mensuel', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant mensuel')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('limite_etudiants', models.IntegerField(default=100, verbose_name="Limite d'étudiants")),
                ('limite_transactions_mois', models.IntegerField(default=1000, verbose_name='Limite de transactions par mois')),
            ],
            options={
                'verbose_name': 'Abonnement',
                'verbose_name_plural': 'Abonnements',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_facture', models.CharField(max_length=50, unique=True, verbose_name='Numéro de facture')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant')),
                ('devise', models.CharField(default='USD', max_length=3, verbose_name='Devise')),
                ('date_emission', models.DateField(auto_now_add=True, verbose_name="Date d'émission")),
                ('date_echeance', models.DateField(verbose_name="Date d'échéance")),
                ('payee', models.BooleanField(default=False, verbose_name='Payée')),
                ('date_paiement', models.DateField(blank=True, null=True, verbose_name='Date de paiement')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-date_emission'],
            },
        ),
    ]
