# Generated by Django 5.2.9 on 2025-12-28 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('abonnements', '0001_initial'),
        ('etablissements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnement',
            name='etablissement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='abonnement', to='etablissements.etablissement', verbose_name='Établissement'),
        ),
        migrations.AddField(
            model_name='facture',
            name='abonnement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='abonnements.abonnement', verbose_name='Abonnement'),
        ),
    ]
