# Generated by Django 5.2.9 on 2025-12-28 16:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etablissements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_frais', models.CharField(max_length=200, verbose_name='Nom des frais')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant')),
                ('devise', models.CharField(choices=[('CDF', 'Franc Congolais (CDF)'), ('USD', 'Dollar Américain (USD)')], default='CDF', max_length=3, verbose_name='Devise')),
                ('annee_academique', models.CharField(max_length=20, verbose_name='Année académique')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frais', to='etablissements.etablissement', verbose_name='Établissement')),
            ],
            options={
                'verbose_name': 'Frais',
                'verbose_name_plural': 'Frais',
                'ordering': ['-date_creation'],
            },
        ),
    ]
